#!/Users/ajesuraj/AppData/Local/Programs/Python/Python36-32/python
print("Content-type:text/html")
print()
print("<html>")
print('<head>')
print('<title>Hello Word - First CGI Program</title>')
print('</head>')
print('<body>')
print('<h2>Hello Word! This is my first CGI program</h2>')
print('</body>')
print('</html>')