bri = set(['Bricks','Sand','Cement'])
print('Sand' in bri)
print("Cement" in bri)
bric = bri.copy()
bric.add("China")
bric.issuperset(bri)
bri.remove('Bricks')
print(bri)
print(bric)
print(bri & bric)
print(bri.intersection(bric))
l1 = ["ant","anna","Susee"]
print("List1 : ",l1)
l2 = l1.copy()
print("List2 : ", l2)
print("List1 : ",l1)
l2[1] = "Anan"
print("List2 : ",l2)
print("List1 : ",l1)
l3 = l2.__add__(["King",])
print("List1 : ",l1)
print("List2 : ",l2)
print("List3 : ",l3)
str1 = "Antony Ananias got offer"
print(list(str1))
print([str1])
print("str1 : ",str1)
str2 = str1.split(" ")
print(str1.split(" "))
print(str1)
print(str2)
str3 = " ".join(str2) + " Welcome to ThinkPalm"
print("Str3 : ",str3)
print("str2 : ",str2)
print("str1 : ",str1)