print("Python is really a great language","isn't it")
x = input("Enter something : ")
fo = open("foo.txt","w")
print("Name of the file : ",fo.name)
print("Closed or Not : ", fo.closed)
print("Opening mode : ", fo.mode)
fo.write(x)
fo.close()
fro = open("is_in.py","r+")
str = fro.read()
print("File : ",str)
fro.close()
